megaphonely/billing/urls.py
from django.urls import path, re_path

from .views import (index, change, subscribe, pricing,
                    perform_change, perform_cancel, perform_subscribe,
                    perform_reactivate)

app_name = 'billing'

urlpatterns = [
    path('', index, name='index'),
    path('pricing/', pricing, name='pricing'),
    re_path(r'^subscribe/(?P<plan>standard|premium)/$', subscribe, name='subscribe'),
    re_path(r'^change/(?P<plan>standard|premium)/$', change, name='change'),
    path('subscribe/', perform_subscribe, name='charge'),
    path('change/', perform_change, name='modify'),
    path('reactivate/', perform_reactivate, name='reactivate'),
    re_path(r'^cancel/(?P<plan>standard|premium)/$', perform_cancel, name='cancel'),
]

megaphonely/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


admin.autodiscover()

if settings.LANDING_PAGE:
    urlpatterns = [
        path('', include('megaphonely.landingpage.urls', namespace='landingpage'))
    ]
else:
    urlpatterns = [
        path('', include('megaphonely.influence.urls', namespace='influence')),
        path('publisher/', include('megaphonely.publisher.urls', namespace='publisher')),
        path('auth/', include('allauth.urls')),
        path('billing/', include('megaphonely.billing.urls', namespace='billing')),
        path('settings/', include('megaphonely.accounts.urls', namespace='accounts')),
        path('pricing/', TemplateView.as_view(template_name='home/pricing.html'), name='pricing'),
        path('privacy/', TemplateView.as_view(template_name='home/privacy.html'), name='privacy'),
        path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
        path('social/', include('social_django.urls', namespace='social')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        path('__6TJny9S332qv92p57585kZdM9srNA66N2s26M39U4M2232B8Uz/', admin.site.urls),
    ]

megaphonely/billing/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save

from .managers import (CustomerManager, SubscriptionManager,
                       PaymentMethodManager, PlanManager)
from .choices import PLANS


def get_trial_ends_at():
    return timezone.now() + timedelta(days=7)


class Plan(models.Model):
    name = models.CharField(max_length=20, choices=PLANS, primary_key=True)
    price = models.IntegerField()
    socials = models.IntegerField()
    contents = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = PlanManager()

    class Meta:
        db_table = 'plans'

    def __str__(self):
        return self.pk


class Customer(models.Model):
    stripe_customer_id = models.CharField(max_length=100, primary_key=True)
    account = models.OneToOneField(settings.AUTH_USER_MODEL,
                                   on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CustomerManager()

    class Meta:
        db_table = 'customers'

    def __str__(self):
        return self.stripe_customer_id

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_user_customer(sender, instance, created, **kwargs):
        if created:
            stripe_customer = Customer.objects.create_stripe_customer(instance)
            stripe_customer_id = stripe_customer['id']
            stripe_subscription = Subscription.objects.create_stripe_subscription(
                'free', stripe_customer_id
            )
            stripe_subscription_id = stripe_subscription['id']
            customer = Customer.objects.create_customer(
                stripe_customer_id, instance
            )
            plan = Plan.objects.get_plan('free')
            Subscription.objects.create_subscription(
                stripe_subscription_id, customer, plan
            )


class PaymentMethod(models.Model):
    stripe_source_id = models.CharField(max_length=100, primary_key=True)
    stripe_last_four = models.CharField(max_length=4)
    stripe_brand = models.CharField(max_length=20)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = PaymentMethodManager()

    class Meta:
        db_table = 'payment_methods'

    def __str__(self):
        return self.stripe_source_id


class Subscription(models.Model):
    stripe_subscription_id = models.CharField(max_length=100, primary_key=True)
    is_active = models.BooleanField(default=False)
    ends_at = models.DateTimeField(default=get_trial_ends_at)
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE,
                                       blank=True, null=True)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = SubscriptionManager()

    class Meta:
        db_table = 'subscriptions'

    def __str__(self):
        return self.stripe_subscription_id

megaphonely/billing/views.py
from django.shortcuts import redirect
from django.conf import settings
from django.template import loader
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from .models import Customer, Subscription, PaymentMethod, Plan


@login_required
def index(request):
    user = request.user
    try:
        customer = user.customer
        template = loader.get_template('billing/index.html')
        context = {}
        response = HttpResponse(template.render(context, request))
        return response
    except ObjectDoesNotExist:
        raise Http404()


@login_required
def pricing(request):
    user = request.user
    template = loader.get_template('pricing.html')
    subscription = user.customer.subscription
    context = {
        'subscription': subscription
    }
    response = HttpResponse(template.render(context, request))

    return response


@login_required
def subscribe(request, plan):
    template = loader.get_template('billing/plan.html')
    plan = Plan.objects.get_plan(plan)
    context = {
        'plan': plan.name,
        'price': plan.price,
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY
    }
    response = HttpResponse(template.render(context, request))

    return response


@login_required
def change(request, plan):
    template = loader.get_template('billing/change.html')
    plan = Plan.objects.get_plan(plan)
    context = {
        'plan': plan.name,
        'price': plan.price
    }
    response = HttpResponse(template.render(context, request))

    return response


@login_required
def perform_cancel(request, plan):
    user = request.user
    plan = Plan.objects.get_plan(plan)
    Subscription.objects.cancel_stripe_subscription(user, plan)
    message = f'Successfully cancelled your plan. ' \
              f'You still have access until ' \
              f'{user.customer.subscription.ends_at.strftime("%B %d, %Y %H:%M")}'
    messages.success(request, message)
    response = redirect('publisher:index')

    return response


@login_required
def perform_change(request):
    user = request.user
    plan_name = request.POST['plan']
    plan = Plan.objects.get_plan(plan_name)
    Subscription.objects.prorotate_stripe_subscription(user, plan)
    message = f'Successfully upgraded to the {plan_name.title()} plan'
    messages.success(request, message)
    response = redirect('publisher:index')

    return response


@login_required
def perform_subscribe(request):
    user = request.user
    payload = request.POST
    plan_name = payload['plan']
    stripe_token = payload['stripeToken']
    stripe_customer = Customer.objects.get_stripe_customer(user)
    payment_method = PaymentMethod.objects.create_stripe_payment_method(
        stripe_token, stripe_customer, user.customer
    )
    plan = Plan.objects.get_plan(plan_name)
    Subscription.objects.update_subscription(user, payment_method, plan)
    message = f'Successfully upgraded to the {plan_name.title()} plan'
    messages.success(request, message)
    response = redirect('publisher:index')

    return response


@login_required
def perform_reactivate(request):
    user = request.user
    Subscription.objects.reactivate_stripe_subscription(user)
    messages.success(request, 'Successfully reactivated plan')
    response = redirect('publisher:index')

    return response

megaphonely/templates/billing/change.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body" style="text-align: center;">
                <h4>{{ plan | title }}</h4>
                {% with template_name=plan|stringformat:"s"|add:".html" %}
                    {% include "includes/billing/plans/"|add:template_name %}
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="col-lg-3"></div>

    <div class="col-lg-3"></div>
    <div class="col-lg-6" style="margin-top: 20px;">
        <form action="{% url 'billing:modify' %}" method="post" id="payment-form">
            {% csrf_token %}
            <small>You will be prorated for any remaining time on your current plan</small>
            <input type="hidden" name="plan" value="{{plan}}">
            <button class="btn btn-primary btn-block" style="margin-top: 10px;">Change to {{ plan | title }}</button>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

{% endblock %}

megaphonely/templates/billing/index.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <div>
                    <h4>Plan</h4>
                    <div class="row">
                        <div class="col-8">
                            {% if user.customer.subscription.is_active %}
                                You are currently on a <strong>{{ user.customer.subscription.plan | title }}</strong> plan
                                which renews on <strong>{{ user.customer.subscription.ends_at.date }}</strong>.
                            {% else %}
                                You are currently on a <strong>{{ user.customer.subscription.plan | title }}</strong> plan
                                which cancels on <strong>{{ user.customer.subscription.ends_at.date }}</strong>.
                            {% endif %}
                        </div>
                        <div class="col-4">
                            <a class="btn btn-primary center" href="{% url 'pricing' %}">Change</a>
                        </div>
                    </div>
                </div>
                <br/>
                <div>
                    <h4>Payment method</h4>
                    <strong>{{ user.customer.subscription.payment_method.stripe_brand }}</strong>
                    ending in
                    <strong>{{ user.customer.subscription.payment_method.stripe_last_four }}</strong>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>
{% endblock %}

megaphonely/templates/billing/plan.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body" style="text-align: center;">
                <h4>{{ plan | title }}</h4>
                {% with template_name=plan|stringformat:"s"|add:".html" %}
                    {% include "includes/billing/plans/"|add:template_name %}
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="col-lg-3"></div>

    <div class="col-lg-3"></div>
    <div class="col-lg-6" style="margin-top: 20px;">
        <form action="{% url 'billing:charge' %}" method="post" id="payment-form">
            {% csrf_token %}
            <div class="form-row form-group">
                <label for="card-element">Credit or debit card</label>
                <div id="card-element" class="form-control"></div>
                <div id="card-errors" role="alert" style="color: red;"></div>
                <small style="padding-top: 10px; padding-bottom: 10px;">
                    You’ll be charged <i class="fas fa-euro-sign" style="font-size: 10px;"></i>{{ price }}.00 monthly until you cancel your subscription.
                    Previous charges won’t be refunded when you cancel unless it’s legally required.
                    Your payment data is encrypted and secure.
                    All amounts shown are in EUR.
                </small>

                <div class="form-check form-group">
                    <input type="checkbox" class="form-check-input" id="tos" required>
                    <label class="form-check-label" for="tos" style="font-size: 14px;">
                        I agree to the <a href="{% url 'terms' %}">Megaphonely Terms</a>
                        and the <strong>Automatic Renewal Terms</strong> above.
                    </label>
                </div>
                <input type="hidden" name="plan" value="{{plan}}">
                <button class="btn btn-success btn-block" style="margin-top: 10px;">Subscribe</button>
          </div>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>
<script type="text/javascript">
    var stripePublicKey = "{{ stripe_public_key }}";
</script>
<script defer type="text/javascript" src="https://js.stripe.com/v3/"></script>
<script defer type="text/javascript" src="{% static 'js/stripe.js' %}"></script>
{% endblock %}

megaphonely/templates/billing/standard.html
{% extends 'layouts/settings.html' %}

{% block setting %}

{% load crispy_forms_tags %}

<div class="col-lg-8 card-section">
    <div class="card">
        <div class="card-header">
            <div class="col-12">
                <div class="row text-center">
                    <div class="col-12">
                        <b>Upgrading to Standard</b>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body text-secondary">
            <form action="{% url 'billing:payment' %}" method="post" id="payment-form">
                {% csrf_token %}
                <input type="hidden" name="plan" value="standard">
                <div class="form-group">
                  <label for="name">Name</label>
                  <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Card name">
                </div>
                <div class="form-row form-group">
                  <label for="card-element">
                    Credit or debit card
                  </label>
                  <div id="card-element" class="form-control"></div>
                  <div id="card-errors" role="alert" style="color: red"></div>
                </div>
                <button class="btn btn-primary btn-block">Pay €19</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

megaphonely/templates/billing/update.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="col-lg-12 card-section">
    <div class="card">
        <div class="card-header">
            <div class="col-12">
                <div class="row text-center">
                    <div class="col-12">
                        <b>Creating content</b>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body text-secondary">
            <div class="card-body text-secondary">
                {% crispy form %}
            </div>
        </div>
    </div>
</div>

{% endblock %}