megaphonely/billing/urls.py
from django.urls import path, re_path

from .views import (index, change, subscribe, pricing,
                    perform_change, perform_cancel, perform_subscribe,
                    perform_reactivate)

app_name = 'billing'

urlpatterns = [
    path('', index, name='index'),
    path('pricing/', pricing, name='pricing'),
    re_path(r'^subscribe/(?P<plan>standard|premium)/$', subscribe, name='subscribe'),
    re_path(r'^change/(?P<plan>standard|premium)/$', change, name='change'),
    path('subscribe/', perform_subscribe, name='charge'),
    path('change/', perform_change, name='modify'),
    path('reactivate/', perform_reactivate, name='reactivate'),
    re_path(r'^cancel/(?P<plan>standard|premium)/$', perform_cancel, name='cancel'),
]

megaphonely/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


admin.autodiscover()

if settings.LANDING_PAGE:
    urlpatterns = [
        path('', include('megaphonely.landingpage.urls', namespace='landingpage'))
    ]
else:
    urlpatterns = [
        path('', include('megaphonely.influence.urls', namespace='influence')),
        path('publisher/', include('megaphonely.publisher.urls', namespace='publisher')),
        path('auth/', include('allauth.urls')),
        path('billing/', include('megaphonely.billing.urls', namespace='billing')),
        path('settings/', include('megaphonely.accounts.urls', namespace='accounts')),
        path('pricing/', TemplateView.as_view(template_name='home/pricing.html'), name='pricing'),
        path('privacy/', TemplateView.as_view(template_name='home/privacy.html'), name='privacy'),
        path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
        path('social/', include('social_django.urls', namespace='social')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        path('__6TJny9S332qv92p57585kZdM9srNA66N2s26M39U4M2232B8Uz/', admin.site.urls),
    ]

megaphonely/views/home.py
from flask import current_app, Blueprint, render_template, jsonify, url_for
from flask_login import current_user

home = Blueprint('home', __name__, url_prefix='/')

@home.route('')
def index():
    template = render_template('home/index.html')
    if current_user.is_authenticated:
        template = render_template('dashboard/index.html')
    return template

@home.route('pricing')
def pricing():
    return render_template('home/pricing.html')

@home.route('terms')
def terms():
    return render_template('home/terms.html')

@home.route('privacy')
def privacy():
    return render_template('home/privacy.html')

@home.route('sitemap')
def sitemap():
    def has_no_empty_params(rule):
        defaults = rule.defaults if rule.defaults is not None else ()
        arguments = rule.arguments if rule.arguments is not None else ()
        return len(defaults) >= len(arguments)

    links = []
    for rule in current_app.url_map.iter_rules():
        # Filter out rules we can't navigate to in a browser
        # and rules that require parameters
        if "GET" in rule.methods and has_no_empty_params(rule):
            url = url_for(rule.endpoint, **(rule.defaults or {}))
            links.append((url, rule.endpoint))
    # links is now a list of url, endpoint tuples

    return jsonify({'links': links})

megaphonely/templates/home/index.html
{% extends 'base.html' %}

{% block body %}

{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load static %}

<h1 class="col-sm-12">Built for product marketers.</h1>
<div class="col-sm-12">
    <p class="lead">
        Find social media influencers to help promote your product.
    </p>
</div>
<div class="col-sm-12">
    <a href="{% url 'pricing' %}" class="btn btn-megaphonely">Start Free Trial</a>
</div>

{% endblock %}

megaphonely/templates/home/pricing.html
{% extends 'base.html' %}

{% block body %}

{% load static %}

<div class="row">
    <div class="col-lg-6 mt-2 text-center">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Standard</h4>
                {% include "includes/billing/plans/standard.html" %}
                {% if not user.is_authenticated %}
                    <a href="{% url 'account_signup' %}" class="btn btn-lg btn-block btn-megaphonely">Start 7 day trial</a>
                {% elif not user.customer.subscription.payment_method %}
                    <a href="{% url 'billing:subscribe' plan='standard' %}" class="btn btn-lg btn-block btn-megaphonely">Choose plan</a>
                {% elif user.customer.subscription.plan.name == 'standard' and user.customer.subscription.is_active %}
                    <a href="{% url 'billing:cancel' plan='standard' %}" class="btn btn-lg btn-block btn-danger">Cancel</a>
                {% elif user.customer.subscription.plan.name == 'standard' and not user.customer.subscription.is_active %}
                    <a href="{% url 'billing:reactivate' %}" class="btn btn-lg btn-block btn-success">Reactivate</a>
                {% elif user.customer.subscription.plan.name != 'standard' %}
                    <a href="{% url 'billing:change' plan='standard' %}" class="btn btn-lg btn-block btn-megaphonely">Change to Standard</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg-6 mt-2 text-center">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Premium</h4>
                {% include "includes/billing/plans/premium.html" %}
                {% if not user.is_authenticated %}
                    <a href="{% url 'account_signup' %}" class="btn btn-lg btn-block btn-megaphonely">Start 7 day trial</a>
                {% elif not user.customer.subscription.payment_method %}
                    <a href="{% url 'billing:subscribe' plan='premium' %}" class="btn btn-lg btn-block btn-megaphonely">Choose plan</a>
                {% elif user.customer.subscription.plan.name == 'premium' and user.customer.subscription.is_active %}
                    <a href="{% url 'billing:cancel' plan='premium' %}" class="btn btn-lg btn-block btn-danger">Cancel</a>
                {% elif user.customer.subscription.plan.name == 'premium' and not user.customer.subscription.is_active %}
                    <a href="{% url 'billing:reactivate' %}" class="btn btn-lg btn-block btn-success">Reactivate</a>
                {% elif user.customer.subscription.plan.name != 'premium' %}
                    <a href="{% url 'billing:change' plan='premium' %}" class="btn btn-lg btn-block btn-megaphonely">Change to Premium</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg-12 mt-2">
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">Our benefits</h1>
                <div class="row">
                    <div class="col-sm-6 mt-3">
                        <img src="{% static 'img/landing-page-2.png' %}" class="img-fluid">
                    </div>
                    <div class="col-sm-6 mt-3 row text-left align-items-center">
                        <div style="padding-left: 20px; padding-right: 20px;">
                            <h4>All-in-One dashboard</h4>
                            <p>Oversee all your social account contents using our dashboard.</p>
                        </div>
                    </div>
                    <div class="col-sm-6 mt-3 text-center">
                        <i class="fab fa-facebook" style="font-size: 70px;"></i>
                        <i class="fab fa-linkedin" style="font-size: 70px;"></i>
                        <i class="fab fa-twitter" style="font-size: 70px;"></i>
                    </div>
                    <div class="col-sm-6 mt-3 row text-left align-items-center">
                        <div style="padding-left: 20px; padding-right: 20px;">
                            <h4>Social accounts</h4>
                            <p>Connect various social platforms.</p>
                        </div>
                    </div>
                    <div class="col-sm-6 mt-3">
                        <img src="{% static 'img/landing-page-1.png' %}" class="img-fluid">
                    </div>
                    <div class="col-sm-6 mt-3 row text-left align-items-center">
                        <div style="padding-left: 20px; padding-right: 20px;">
                            <h4>Schedulable contents</h4>
                            <p>Schedule contents to be posted tomorrow, a week or a month from now.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

megaphonely/templates/home/privacy.html
{% extends 'base.html' %}

{% block body %}

<div class="card">
    <div class="card-body">
        <h1 style="text-align: center;">Privacy (effective as of March, 8 2018)</h1>
        <p>
            Megaphonely provides this Privacy Policy to inform users of our policies and procedures regarding the
            collection, use and disclosure of personally identifiable information received from users of this
            website, located at https://megaphonely.com ("Site" ).
        </p>

        <p>
            By using our Site you are consenting to our processing of your information as set forth in this
            Privacy Policy now and as amended by us. "Processing" means using cookies on a computer or
            using or touching information in any way, including, but not limited to, collecting, storing,
            deleting, using, combining and disclosing information, all of which activities will take place in
            Ireland. If you reside outside Ireland your personally identifiable information will be
            transferred to Ireland, and processed and stored there under Ireland privacy standards.

            By visiting our Site and providing information to us, you consent to such transfer to, and
            processing in the UK.
        </p>

        <strong>Information Collection and Use</strong>

        <p>
            Our primary goals in collecting personally identifiable information are to provide you with the
            product and services made available through the Site, including, but not limited, to the Service,
            to communicate with you, and to manage your registered user account, if you have one.
        </p>

        <strong>Information Collected Upon Registration</strong>

        <p>
            If you desire to have access to certain restricted sections of the Site, you will be required to
            become a registered user, and to submit certain personally identifiable information to Megaphonely.
            This happens in a number of instances, such as when you sign up for the Service, or if you
            desire to receive marketing materials and information. Personally identifiable information that we
            may collect in such instances may include your IP address, full user name, password, email
            address, city, time zone, telephone number, and other information that you decide to provide us
            with.
        </p>


        <strong>Use of Contact Information</strong>

        <p>
            In addition, we may use your contact information to market to you, and provide you with
            information about, our products and services, including but not limited to our Service. If you
            decide at any time that you no longer wish to receive such information or communications from
            us, please un­follow us, or follow the unsubscribe instructions provided in any of the
            communications.
        </p>


        <strong>Log Data</strong>


        <p>
            When you visit the Site, our servers automatically record information that your browser sends
            whenever you visit a website ("Log Data" ). This Log Data may include information such as your
            IP address, browser type or the domain from which you are visiting, the web­pages you visit, the
            search terms you use, and any advertisements on which you click. For most users accessing
            the Internet from an Internet service provider the IP address will be different every time you log
            on. We use Log Data to monitor the use of the Site and of our Service, and for the Site’s
            technical administration. We do not associate your IP address with any other personally
            identifiable information to identify you personally, except in case of violation of the Terms of
            Service.
        </p>

        <strong>Cookies</strong>

        <p>
            Like many websites, we also use "cookie" technology to collect additional website usage data
            and to improve the Site and our service. A cookie is a small data file that we transfer to your
            computer's hard disk. We do not use cookies to collect personally identifiable information.
            Megaphonely may use both session cookies and persistent cookies to better understand how you
            interact with the Site and our Service, to monitor aggregate usage by our users and web traffic
            routing on the Site, and to improve the Site and our services. A session cookie enables certain
            features of the Site and our service and is deleted from your computer when you disconnect
            from or leave the Site. A persistent cookie remains after you close your browser and may be
            used by your browser on subsequent visits to the Site. Persistent cookies can be removed by
            following your web browser help file directions. Most Internet browsers automatically accept
            cookies. You can instruct your browser, by editing its options, to stop accepting cookies or to
            prompt you before accepting a cookie from the websites you visit.
        </p>

        <strong>Service Providers</strong>

        <p>
            We engage certain trusted third parties to perform functions and provide services to us,
            including, without limitation, hosting and maintenance, billing, customer relationship, database
            storage and management, and direct marketing campaigns. We will share your personally
            identifiable information with these third parties, but only to the extent necessary to perform these
            functions and provide such services, and only pursuant to binding contractual obligations
            requiring such third parties to maintain the privacy and security of your data.
        </p>

        <strong>Compliance with Laws and Law Enforcement</strong>

        <p>
            Megaphonely cooperates with government and law enforcement officials or private parties to enforce
            and comply with the law. We may disclose any information about you to government or law
            enforcement officials or private parties as we, in our sole discretion, believe necessary or
            appropriate to respond to claims, legal process (including subpoenas), to protect the property
            and rights of Megaphonely or a third party, the safety of the public or any person, to prevent or stop
            any illegal, unethical, or legally actionable activity, or to comply with the law.
        </p>


        <strong>Business Transfers</strong>


        <p>
            Megaphonely may sell, transfer or otherwise share some or all of its assets, including your personally
            identifiable information, in connection with a merger, acquisition, reorganization or sale of assets
            or in the event of bankruptcy. You will have the opportunity to opt out of any such transfer if the
            new entity's planned processing of your information differs materially from that set forth in this
        </p>


        <strong>Changing or Deleting Information</strong>

        <p>
            If you are a registered user of the Site, you may access and update or correct the information
            you provided to us by e­mailing us at support@megaphonely.com.
        </p>

        <strong>Security</strong>

        <p>
            Megaphonely is very concerned about safeguarding the confidentiality of your personally identifiable
            information. We employ administrative, physical and electronic measures designed to protect
            your information from unauthorized access. We will make any legally­required disclosures of
            any breach of the security, confidentiality, or integrity of your unencrypted electronically stored
            personal data to you via email or conspicuous posting on this Site in the most expedient time
            possible and without unreasonable delay, consistent with (i) the legitimate needs of law
            enforcement or (ii) any measures necessary to determine the scope of the breach and restore
            the reasonable integrity of the data system.
        </p>


        <strong>Links to Other Websites</strong>


        <p>
            Our Site contains links to other websites. The fact that we link to a website is not an
            endorsement, authorization or representation of our affiliation with that third party. We do not
            exercise control over third party websites. These other websites may place their own cookies or
            other files on your computer, collect data or solicit personally identifiable information from you.
            Other sites follow different rules regarding the use or disclosure of the personally identifiable
            information you submit to them. We encourage you to read the privacy policies or statements of
            the other websites you visit.
        </p>


        <strong>Our Policy Towards Children</strong>

        <p>
            The Site is not directed to persons under 13. If a parent or guardian becomes aware that his or
            her child has provided us with personally identifiable information without their consent, he or she
            should contact us at support@megaphonely.com. We do not knowingly collect personally identifiable
            information from children under 13. If we become aware that a child under 13 has provided us
            with personal identifiable Information, we will delete such information from our files.
        </p>

        <strong>Changes to this Policy</strong>

        <p>
            This Privacy Policy may be updated from time to time for any reason; each version will apply to
            information collected while it was in place. We will notify you of any material changes to our
            Privacy Policy by posting the new Privacy Policy on our Site. You are advised to consult this
            Privacy Policy regularly for any changes.
            If you have any thoughts or questions about this Privacy Policy please let us know.
        </p>
    </div>
</div>

{% endblock %}