megaphonely/landingpage/urls.py
from django.urls import path

from .views import index

app_name = 'landingpage'

urlpatterns = [
    path('', index, name='index'),
]

megaphonely/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


admin.autodiscover()

if settings.LANDING_PAGE:
    urlpatterns = [
        path('', include('megaphonely.landingpage.urls', namespace='landingpage'))
    ]
else:
    urlpatterns = [
        path('', include('megaphonely.influence.urls', namespace='influence')),
        path('publisher/', include('megaphonely.publisher.urls', namespace='publisher')),
        path('auth/', include('allauth.urls')),
        path('billing/', include('megaphonely.billing.urls', namespace='billing')),
        path('settings/', include('megaphonely.accounts.urls', namespace='accounts')),
        path('pricing/', TemplateView.as_view(template_name='home/pricing.html'), name='pricing'),
        path('privacy/', TemplateView.as_view(template_name='home/privacy.html'), name='privacy'),
        path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
        path('social/', include('social_django.urls', namespace='social')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('admin/', admin.site.urls),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        path('__6TJny9S332qv92p57585kZdM9srNA66N2s26M39U4M2232B8Uz/', admin.site.urls),
    ]

megaphonely/landingpage/models.py
from django.db import models

from .choices import KINDS, CATEGORIES
from .managers import CharlieManager


class Charlie(models.Model):
    email = models.EmailField(unique=True)
    kind = models.CharField(max_length=20, choices=KINDS)
    category = models.CharField(max_length=100, choices=CATEGORIES)
    objects = CharlieManager()

    def __str__(self):
        return self.email

megaphonely/landingpage/forms.py
from django import forms

from .models import Charlie
from .choices import KINDS, CATEGORIES


class CharlieForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email address'
        }),
        label='What is your email?'
    )
    kind = forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'form-control'}),
        choices=KINDS,
        label='What kind of business are you?'
    )
    category = forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'form-control'}),
        choices=CATEGORIES,
        label='Which category do you primary target?'
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        email = cleaned_data['email']

        if email and Charlie.objects.email_exists(email):
            msg = f"{email} is already registered"
            raise forms.ValidationError(msg)

        return cleaned_data

megaphonely/landingpage/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings

from .models import Charlie
from .forms import CharlieForm


def index(request):
    if request.method == 'POST':
        form = CharlieForm(request.POST)
        if form.is_valid():
            payload = request.POST
            charlie = Charlie(
                email=payload['email'],
                kind=payload['kind'],
                category=payload['category']
            )
            charlie.save()

            msg = f"Thanks for signing up {payload['email']}!"
            subject = 'Megaphonely'
            html_message = """
                <img src='https://assets.megaphonely.com/static/email/megaphonely.png'>
                <br/>
                <strong>Thanks for joining the Megaphonely mailing list!</strong>
                <p>
                    You'll be updated on the latest developments of Megaphonely. Also, you can reply to this email if you want to suggest a feature or an idea that you'd like implemented.
                </p>
            """

            send_mail(
                subject=subject,
                message=html_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[payload['email']],
                html_message=html_message
            )
            messages.success(request, msg)
    else:
        form = CharlieForm()
    context = {'form': form}
    return render(request, 'landingpage/index.html', context)

megaphonely/templates/landingpage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#990000">
    <meta name="msapplication-TileImage" content="{% static 'img/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#990000">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Megaphonely</title>
    <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Work+Sans'>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
</head>
<body>
    <wrapper class="d-flex flex-column">
        <main class="flex-fill">
            <div class="container mt-3">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                {% endfor %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% for field in form.visible_fields %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="container">
                {% block body %} {% endblock %}
            </div>
        </main>
        {% include 'landingpage/footer.html' %}
</body>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript">window.jQuery || document.write('<script src="{% static 'js/jquery.js' %}"><\/script>')</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</html>

megaphonely/templates/landingpage/footer.html
<ul class="nav justify-content-center">
  <li class="nav-item"><a class="nav-link disabled">Made with <i class="fa fa-heart" style="color: red;"></i> in Dublin</a></li>
  <li class="nav-item"><a class="nav-link" href="https://www.twitter.com/megaphonely"><i class="fab fa-twitter"></i></a></li>
  <li class="nav-item"><a class="nav-link" href="https://www.facebook.com/Megaphonely-723749727830922"><i class="fab fa-facebook"></i></a></li>
  <li class="nav-item"><a class="nav-link" href="https://www.instagram.com/megaphonely"><i class="fab fa-instagram"></i></a></li>
  <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com/company/megaphonely"><i class="fab fa-linkedin"></i></a></li>
  <li class="nav-item"><a class="nav-link disabled">© 2018 Megaphonely</a></li>
</ul>

megaphonely/templates/landingpage/index.html
{% extends 'landingpage/base.html' %}
{% load static %}
{% block body %}

<div class="row mt-3">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <div class="card">
            <div class="card-body">
                <div class="col-lg-12 text-center mb-3">
                    <a class="header-logo" href="/">
                        <img src="{% static 'img/mstile-310x310.png' %}" height="40" width="40" class="text-center"><span style="color: #33334F; font-size: 27px;">megaphonely</span>
                    </a>
                </div>
                <div class="col-lg-12">
                    <p class="text-center">
                        Megaphonely simplifies how brands reach Irish social media influencers.
                    </p>
                    <div class="row">
                        <div class="col-sm-12">
                            <strong>Upcoming features</strong>
                            <li>Find social media influencers by their location.</li>
                            <li>Filter influencers based on category, metrics, etc.</li>
                        </div>
                    </div>
                    <img src="{% static 'img/howmegaphonelyworks.png' %}" class="img-fluid mb-3"/>
                </div>
                <div class="col-lg-12 mb-2">
                    <div class="text-center">
                        <small>
                            The app hasn't launched yet but I'd be happy
                            to keep you updated when it does
                            (your email won't be used for anything else.)
                        </small>
                    </div>
                    <form action="{% url 'landingpage:index' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12 mb-2 mt-3">
                                {{ form.email.label }}
                                {{ form.email }}
                            </div>
                            <div class="col-lg-12 mb-2">
                                {{ form.kind.label }}
                                {{ form.kind }}
                            </div>
                            <div class="col-lg-12 mb-2">
                                {{ form.category.label }}
                                {{ form.category }}
                            </div>
                            <div class="col-lg-12">
                                <input type="submit" class="btn btn-megaphonely btn-block" value="Subscribe"/>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-2"></div>
</div>
{% endblock %}